" set dirs
set backupdir=$HOME/.vim/swap/backup//
set undodir=$HOME/.vim/swap/undo//
set directory=$HOME/.vim/swap//

"jumphax
set iskeyword+=_,$,@,%,#

"global
set t_Co=256

set shell=/bin/zsh

"source $HOME/.vim/neobundle.vim
source $HOME/.vim/vimplug.vim
source $HOME/.vim/profile.vim
source $HOME/.vim/mappings.vim
"set rtp+=~/.fzf
set backspace=2 
set synmaxcol=150
