#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#xrdb -merge ~/.Xresources
xrdb -load .Xresources


#fonts
/etc/X11/xinit/xinitrc.d/infinality-settings
xset +fp /usr/share/fonts/artwiz-fonts/
xset +fp /usr/share/fonts/misc/
xset +fp /usr/share/fonts/TTF/
xset +fp /usr/share/fonts/local/

xset fp rehash

#vars
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export _JAVA_AWT_WM_NONREPARENTING=1
export VDPAU_NVIDIA_NO_OVERLAY=1

#export PATH=$PATH:$HOME/bin


if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setxkbmap se

#init shit
mopidy &
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

urxvtd &

nvidia-settings --load-config-only
exec herbstluftwm

